<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" />
		<PackageReference Include="Caching.FileBackedDistributedCache" />
		<PackageReference Include="DamianH.FileDistributedCache" />
		<PackageReference Include="LiteDb.Extensions.Caching" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
		<PackageReference Include="NeoSmart.Caching.Sqlite.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Extensions.Caching.FileSystem\Extensions.Caching.FileSystem.csproj" />
	</ItemGroup>

</Project>
